import type { Metadata } from "next";
import { Dela_Gothic_One, Montserrat } from "next/font/google";
import "./globals.css";

const dela_gothic_one = Dela_Gothic_One({
  variable: "--font-dela-gothic-one",
  subsets: ["latin"],
  weight: ["400"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dela_gothic_one.variable} ${montserrat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
